export const USER_STATE_CHANGE = "USER_STATE";
export const USER_POSTS_STATE_CHANGE = "USER_POSTS_STATE";
export const USER_FOLLOWING_STATE_CHANGE = "USER_POSTS_STATE";

export const USERS_POSTS_STATE_CHANGE = "USERS_POSTS_STATE_CHANGE";
export const USERS_DATA_STATE_CHANGE = "USERS_DATA_STATE_CHANGE";